---
- name: Instalacao do servidor apache
  hosts: all
  tasks:
  - name: Instalar httpd
    yum:
      name: httpd
      state: present

  - name: Start httpd
    service:
      name: httpd
      state: started

  - name: Copiar index
    copy:
      src: /var/lib/awx/index.html
      dest: /var/www/html/index.html

  - name: Abrir porta httpd
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes
