---
- name: Subscrição da máquina e Update de pacotes
  hosts: all
  tasks:
  - name: Subscrição
    redhat_subscription:
      state: present
      username: someuser
      password: somepass
      auto_attach: true
